AllCops:
  RunRailsCops: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'config/initializers/*'
   - 'config/environments/*'
   - 'db/**/**'
Documentation:
  Enabled: false
#Style/MultilineOperationIndentation:
#  EnforcedStyle: indented

